### ISSUE TITLE
Implement Scrolling/Elements rolling up on Rap/Referral Page

### ISSUE THREAD

**Issue by Peekaey** [Peekaey/Mobile-App-SWNG#31]
Currently when the keyboard appears in the rap/referral page, the notes field for example is covered by the keyboard which stops the users from being able to see what they are inputting.

Looking to implement ScrollView to move the elements upwards once the keyboard appears to make it easier to preview what the user is entering

**Comment by Naitik0121** [comment]
its done, used scrollview elements from react native

**Comment by Peekaey** [comment]
fixed
