### ISSUE TITLE
Fix Keyboard popup squishing screen elements - change to render over webpage 

### ISSUE THREAD

**Issue by Peekaey** [Peekaey/Mobile-App-SWNG#7]

**Comment by Peekaey** [comment]
Example of Keyboard rendering with the bottom status bar attached below

Need the Keyboard to render over the bottom status bar




![image](https://github.com/Peekaey/Mobile-App-SWNG/assets/64738072/4304230c-5a17-42d4-b37e-d89dbcf4aa7b)

![image](https://github.com/Peekaey/Mobile-App-SWNG/assets/64738072/19930719-adfb-42f7-84f6-f6c95a891710)

**Comment by Peekaey** [comment]
Fixed for all pages besides rap/referral page

**Comment by Naitik0121** [comment]
done
